 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: myapi-ingres
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: myapihost
     http:
       paths:
       - path: /
         backend:
           serviceName: myapi
           servicePort: 8000
